spring:
  datasource:
    url: jdbc:mysql://rm-2zetd9474ydd1g5955o.mysql.rds.aliyuncs.com:3306/test?useSSL=false&serverTimezone=UTC
    username: workshop
    password: Workshop123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true