server:
  port: 8080
spring:
  application:
    name: service-customer
feign:
  hystrix:
    enabled: true
info:
  app:
    name: service-customer
    description: 这是描述 这是一个消费者
eureka:
  client:
    service-url:
      # defaultZone: http://eureka-server1:7000/eureka/ 单机
      # 集群
      defaultZone: http://eureka-server1:7000/eureka/,http://eureka-server2:7001/eureka/,http://eureka-server3:7002/eureka/
  instance:
    instance-id: service-customer:8080 #注册地址title
    prefer-ip-address: true #鼠标放到注册地址上可以显示ip