#tomcat 端口
server:
  port: 8080
#spring 配置
spring:
  datasource:
    url: jdbc:mysql://192.168.80.129:3306/workflow?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.state.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: 192.168.8.130:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
#dubbo 配置
dubbo:
  application:
    name: szb-platform-workflow
    owner: Wang.hm
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.8.133:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.8.133:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.szb.platform.workflow.service

hj:
  tx:
    pointcut-expression: execution(* com.szb.platform.workflow.service..*.*(..))
#连接池 配置
druid:
  filter:
    commons-log:
      statement-log-enabled: true
      statement-executable-sql-log-enable: true

