spring:
  datasource:
    url: jdbc:mysql://120.78.78.122:3306/szb_haiqi?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: szb-db-#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.state.slowSqlMillis=500
    useGlobalDataSourceStat: true

  redisson:
    mode: cluster
    password: szb-redis-#@!
    timeout: 3000
    database: 0
    cluster:
      nodes: 172.18.58.9:6379,172.18.58.9:6380,172.18.58.9:6381,172.18.241.246:6379,172.18.241.246:6380,172.18.241.246:6381,172.18.58.8:6379,172.18.58.8:6380,172.18.58.8:6381
      read-mode: SLAVE
      scan-interval: 1000
      retry-attempts: 3
      failed-slave-check-interval: 3
      master-connection-pool-size: 64
      slave-connection-pool-size: 64
      retry-interval: 1500
    pool:
      max-idle: 10
      min-idle: 4
      max-active: 10
      max-wait: 3000
      conn-timeout: 3000
      so-timeout: 3000
      size: 20

dubbo:
  application:
    name: szb-platform-task
    owner: LHY
  protocol:
    name: dubbo
    port: 30005
  registry:
    address: 172.18.58.9:2181
    protocol: zookeeper
    check: false
    group: dubbo-prod
    simplified: true
  metadata-report:
    address: zookeeper://172.18.58.9:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-prod
  scan:
    base-packages: com.szb.platform.task.rpc

swagger:
  basic:
    enable: true
    username: admin
    password: admin
  #production: true

hj:
  tx:
    pointcut-expression: execution(* com.szb.cost.budget.service..*.*(..))