server:
  port: 7777

spring:
  application:
    name: server-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: server-zuul:7777
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: SERVICE-PROVIDER
    mydept.path: /serviceprovider/**

info:
  app:
    name: server-zuul
    description: 这是描述 这是个网关