spring:
  jpa:
    show-sql: true
  datasource:
    embeddedDatabaseConnection: h2
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
