spring:
  datasource:
    url: jdbc:mysql://192.168.6.192:3306/lsxd_recharge_mall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lsxddb123.
    driver-class-name: com.mysql.jdbc.Driver

