spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    org.springframework.web: WARN
    org.flowable: WARN

flowable:
  async-executor-activate: false
  activity-font-name: 宋体
  label-font-name: 宋体
  annotation-font-name: 宋体
  history-level: full